# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CERN.
#
# invenio-app-ils is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

language: python

python: "3.6"

cache:
  - pip

addons:
  postgresql: "12.4"

services:
  - redis
  - rabbitmq

notifications:
  email: false

env:
  global:
    - ES6_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.0.tar.gz"
    - ES7_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.3.0-linux-x86_64.tar.gz"
    - EXTRAS_COMMON=all,postgresql

####################################################################################################################
# Define common anchors
####################################################################################################################

_common: &common
  stage: test
  before_install:
    - "mkdir /tmp/elasticsearch"
    - "wget -O - $ES_URL | tar xz --directory=/tmp/elasticsearch --strip-components=1"
    - "/tmp/elasticsearch/bin/elasticsearch --quiet &"
    - "travis_retry pip install --upgrade pip setuptools py"
    - "travis_retry pip install twine wheel coveralls requirements-builder 'six>=1.12.0'"  # pinning min `six` version is required here because some Ubuntu dist in Travis comes with an older version already installed
    - "requirements-builder -e $EXTRAS --level=min setup.py > .travis-lowest-requirements.txt"
    - "requirements-builder -e $EXTRAS --level=pypi setup.py > .travis-release-requirements.txt"
  install:
    - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
    - "travis_retry pip install -e .[$EXTRAS]"
  before_script: "./run-style-checks.sh"
  script: skip # to be overridden when declaring the job
  after_success: coveralls

_env_release_es6: &env_release_es6
  env: REQUIREMENTS=release EXTRAS=$EXTRAS_COMMON,elasticsearch6 ES_URL=$ES6_DOWNLOAD_URL
_env_release_es7: &env_release_es7
  env: REQUIREMENTS=release EXTRAS=$EXTRAS_COMMON,elasticsearch7 ES_URL=$ES7_DOWNLOAD_URL
_env_lowest_es6: &env_lowest_es6
  env: REQUIREMENTS=lowest EXTRAS=$EXTRAS_COMMON,elasticsearch6 ES_URL=$ES6_DOWNLOAD_URL
_env_lowest_es7: &env_lowest_es7
  env: REQUIREMENTS=lowest EXTRAS=$EXTRAS_COMMON,elasticsearch7 ES_URL=$ES7_DOWNLOAD_URL

jobs:
  include:
    ####################################################################################################################
    # RELEASE - ES7
    ####################################################################################################################
    - <<: *common
      name: "requirements: release | es: 7 | tests: acquisition"
      <<: *env_release_es7
      script: "./run-tests.sh acquisition"
    - <<: *common
      name: "requirements: release | es: 7 | tests: circulation"
      <<: *env_release_es7
      script: "./run-tests.sh circulation"
    - <<: *common
      name: "requirements: release | es: 7 | tests: document requests"
      <<: *env_release_es7
      script: "./run-tests.sh document_requests"
    - <<: *common
      name: "requirements: release | es: 7 | tests: ill"
      <<: *env_release_es7
      script: "./run-tests.sh ill"
    - <<: *common
      name: "requirements: release | es: 7 | tests: ils"
      <<: *env_release_es7
      script: "./run-tests.sh ils"
